### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by manukd** [perarnborg/vuex-oidc-example-nuxt#1]
Hi, i've an error when i run dev this projet.
My error is as follows : 
![image](https://user-images.githubusercontent.com/29897553/60646171-f5c30000-9e3a-11e9-804a-c7696a710a3f.png)
The store "oidc.js" isn't recognized like a object therefore the page does not load.
Have you a solution of that issue ? 

EDIT : I also have too this warning in my console :
![image](https://user-images.githubusercontent.com/29897553/60646503-ce206780-9e3b-11e9-8c1a-f0c33c0e75d9.png)

Ty and have good day !

**Comment by dschox** [comment]
Are you on the latest version of vuex-oidc?
When we cloned this example and copied files to our project it crashed, too (don't know if we had the same error back then). Updating the vuex-oidc dependency to the latest version fixed that. Current version is 2.0.1 but the version in this example is 1.15.3

@perarnborg can you update the example?

**Comment by manukd** [comment]
Thank you :D (i'm so stupid ...)

**Comment by perarnborg** [comment]
Sorry about this and thanks for helping out @dschox! I’ll reopen this issue and fix the dependency version as soon as I get to a computer next week!

**Comment by perarnborg** [comment]
OK, this vuex-oidc version of this example is now in sync!
