### ISSUE TITLE
silent-renew-oidc.html

### ISSUE THREAD

**Issue by manukd** [perarnborg/vuex-oidc-example-nuxt#2]
Hi, it's me ... 
I have a question about the silent renew in with nuxt, we put this information on the config file "oidc.js" 
![image](https://user-images.githubusercontent.com/29897553/60729911-2347a080-9f44-11e9-8307-fdec6db33f05.png)
But i don't understand where this page is defined or where we declare it ? 

Have a good day, bye !

**Comment by israelfloresdga** [comment]
I'm also having some issues with silent-renew but I'm using it with a vue file. Maybe including how to use it in the example...

**Comment by larzon83** [comment]
You have to create this html-file on your own inside the static Folder of your nuxt project.
Enter basic html inside with empty body. It will be dynamicly filled by the library.

**Comment by manukd** [comment]
I have create the html file and static folder and the resquest is sent on the provider but the token still expires, i have a white page and i need to refresh for have a new token.

![image](https://user-images.githubusercontent.com/29897553/60789464-75b0d900-a15f-11e9-95bf-1c291bdb4621.png)

And in my network : 
![image](https://user-images.githubusercontent.com/29897553/60789711-07204b00-a160-11e9-9ba1-74e0d389ce34.png)

**Comment by manukd** [comment]
I just placed the HTML at the root of my project and created the file silent-renew-oidc.js and I have a correct renewal of my token 
![image](https://user-images.githubusercontent.com/29897553/60822567-fb577780-a1a5-11e9-8b36-606d96a4f2b9.png)
