### ISSUE TITLE
Redirect Loop when router base is a subfolder

### ISSUE THREAD

**Issue by dschox** [perarnborg/vuex-oidc-example-nuxt#6]
There is a bug in the getOidcCallbackPath function. If router base is a subfolder (eg /app/), then the callback from the identity server will trigger a redirect loop.

This is because the check for valid callback-route in routeIsOidcCallback (line 183) will always fail.
route.path === oidcCallbackPath will never match.
eg.
route.path is "oidc-callback/"
and oidcCallbackPath (set within getOidcCallbackPath) is "app/oidc-callback/"

The getOidcCallbackPath function needs to ckeck if router base is different then "/" and calculate the substring accordingly.

**Comment by perarnborg** [comment]
Thanks for debuging help, and sorry for this mistake! Will fix asap!

**Comment by perarnborg** [comment]
This issue is fixed as of v2.0.2. If any other route base than / (default) is used you need to pass the routeBase as a setting when the vuex module is created. See https://github.com/perarnborg/vuex-oidc/wiki#2-setup-vuex for refernce.
