### ISSUE TITLE
trailing slash in publicRoutePaths

### ISSUE THREAD

**Issue by dschox** [perarnborg/vuex-oidc-example-nuxt#7]
I defined some public routes within the publicRoutePaths-array in the store module (e.g. "/imprint"). However, if I change the URL in the browser to have a trailing slash ("app.com/imprint/") I get redirected to my Identity Provider.
I encountered this on our live system, because nginx adds a trailing slash for all routes.
To get it working, I now have two entries per route in the publicRoutePaths-array (eg "/imprint" and "/imprint/").
Is it possible to fix/change this behaviour? Or do I did something wrong?

THX!

**Comment by perarnborg** [comment]
@dschox This is a bug, thanks for reporting it. Trailing slash or not should not matter, and a fix for this will be up soon.

**Comment by perarnborg** [comment]
@dschox Should be fixed in v2.0.3

**Comment by dschox** [comment]
I updated to 2.0.3 and it's working nicely :) Thx for the quick fix!
